CREATE TABLE `quote_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`company` text NOT NULL,
	`contact_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`project_type` text NOT NULL,
	`material` text,
	`profile` text,
	`quantity` integer,
	`radius` text,
	`timeline` text,
	`notes` text,
	`file_key` text,
	`file_name` text,
	`file_type` text,
	`file_size` integer
);
